---
version: '3.8'
services:
  n8n:
    container_name: n8n
    ports:
      - 5678:5678
    environment:
      - WEBHOOK_URL=ip/url
      - EXECUTIONS_PROCESS=main
    volumes:
      - ./.n8n:/home/node/.n8n
    image: n8nio/n8n
    restart: unless-stopped