name: Update Docker Compose

on:
  workflow_dispatch:

jobs:
  update-compose:
    runs-on:
      - self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for updates in docker-compose and update containers
      run: |
        sudo cd /opt/docker
        sudo docker-compose pull
        sudo docker-compose up -d